---
- name: Converge 
  hosts: all
  # vars:
  #   root: "/root/"
  tasks:
    - name: install updates
      command: apt update -y #cmd for updates on ubuntu

    - name: install git # installing git on both containers
      apt:
        name: git
        state: present
        update_cache: yes
    
    - name: install tree #installing tree
      command: sudo apt-get install tree
      # apt:
      #   name: tree
      #   state: present
      #   update_cache: yes

    - name: clone repo # cloning a repo
      ansible.builtin.git:
        repo: https://github.com/AB-Sterling-b2bi/multi-tenancy-gitops.git
        dest: /root/gitops/multi-tenancy
    #
    - name: add text to README.md file
      blockinfile:
        path: "root/gitops/multi-tenancy/README.md"
        block: |
          # I AM HERE
    #
    # - name: create sh script
    #   file:
    #     path: "{{ x }}script.sh"
    #     state: touch
    #
    # - name: insert text into script
    #   lineinfile:
    #     path: "{{ x }}script.sh"
    #     line: "pip install --upgrade pip"
    #
    # - name: set executable permission for script.sh
    #   ansible.builtin.file:
    #     path: "{{ x }}script.sh"
    #     state: touch
    #     mode: u=rwx,g=rwx,o=rwx

#multi-tenancy-gitops/blob/master/0-bootstrap/single-cluster/1-infra/kustomization.yaml